-- ============================================================================
--  MODULO DFe - PARAMETRIZACAO DAS TELAS (ARQUIVO 03_01)
-- ============================================================================
--  As tres tabelas que o BLOCO DE TELAS usa: quem ve o que, e a partir de
--  quantos dias a nota pendente aparece como atrasada.
--
--      dpc_dfe_usuario_empresa    quais filiais o usuario ve
--      dpc_dfe_usuario_aba        quais categorias o usuario ve
--      dpc_dfe_painel_alerta      limiar de dias por filial
--
--  Como POSEIDON, arquivo inteiro com Alt+X. LIGUE O DBMS_OUTPUT: cada bloco
--  informa o que fez, e num arquivo que renomeia coisa isso importa.
--
--  ==========================================================================
--   O MODULO TEM DOIS BLOCOS
--  ==========================================================================
--      dfe  (modulo)
--       |-- MOTOR   as 13 tabelas dpc_dfe_*, criadas pelo 01_01. Captura de
--       |           documento na SEFAZ e no ADN. Nao tem conceito de usuario:
--       |           e CLI e banco, sem sessao e sem login.
--       |
--       '-- TELAS   estas tres. Permissao de acesso aos paineis e o limiar de
--                   alerta que eles usam para pintar a linha.
--
--  Por isso o motor NAO leva rotulo no nome e estas levam: o motor e o assunto
--  proprio do modulo, e o que precisa de rotulo e o bloco anexo. Qualquer
--  tabela com "usuario" no nome, dentro deste modulo, e necessariamente de
--  tela - o motor nao sabe o que e um usuario.
--
--  ==========================================================================
--   POR QUE ESTE ARQUIVO EXISTE
--  ==========================================================================
--  Estas tres nasceram no card #3235, pelo lado do front, e ficaram fora de
--  qualquer script: foram criadas A MAO em 25/08/2026 e NENHUM .sql do
--  workspace as criava - conferido em toda a arvore, em .sql, .php e .md.
--
--  Sobreviveram ao refresh da base de teste de 09/09/2026 por SORTE: o
--  snapshot restaurado era de 27/08, dois dias depois de elas existirem. Com
--  um snapshot mais antigo, elas teriam sumido - e a tela nao daria erro. O
--  repositorio curto-circuita quando o usuario nao tem permissao e devolve
--  HTTP 200 com lista vazia, que e indistinguivel de "nao ha nota no periodo".
--
--  ==========================================================================
--   ESTE ARQUIVO E CONVERGENTE
--  ==========================================================================
--  Leva qualquer base ao estado certo, e roda quantas vezes quiser:
--
--    base com os nomes ANTIGOS (dpc_sefaz_*)  -> secao 1 renomeia
--    base sem nenhuma das tabelas             -> secao 2 cria
--    base ja no estado final                  -> tudo no-op
--
--  Nao existe script de migracao separado de proposito. Foi ter dois caminhos
--  para o mesmo fim - instalar x atualizar - que custou dias neste modulo.
--
--  ==========================================================================
--   O QUE NAO MUDA, E POR QUE
--  ==========================================================================
--  NOME DE COLUNA. As colunas fogem da convencao do modulo (id, nroempresa,
--  usuario, dias, cor_no_periodo - sem cod_/nro_/dsc_/dta_). Ficam como estao:
--  cor_no_periodo e cor_fora_periodo sao lidas PELO NOME no front
--  (DPC/src/app/sefaz/documentos-fiscais/components/Main.vue), e nroempresa
--  aparece em 237 arquivos do DPC - e convencao do banco legado, nao descuido
--  local. Renomear coluna ripplearia no payload da API e no front, sem ganho
--  proporcional. A divergencia fica REGISTRADA nos comentarios da secao 4.
--
--  A PK id, que e IDENTITY COLUMN (generated by default as identity) em vez do
--  trigger + sequence do resto do modulo. Trocar mudaria o contrato dos tres
--  repositorios que fazem insert. E identity nao e exotico aqui: 43 das 1.098
--  tabelas do schema usam.
-- ============================================================================


-- ###########################################################################
--  0. DIAGNOSTICO
--  Somente leitura. Diz em que estado a base esta ANTES de mexer.
-- ###########################################################################
--  ESPERADO em base que ainda nao passou por este arquivo: as tres linhas
--  antigas com "existe" e as tres novas com "ausente".
select nome, case when qtd = 0 then 'ausente' else 'existe' end as situacao
  from (
    select 'dpc_sefaz_usuario_empresa (antigo)' as nome, 1 as ord,
           (select count(*) from all_tables
             where owner = 'POSEIDON' and table_name = 'DPC_SEFAZ_USUARIO_EMPRESA') as qtd
      from dual
    union all
    select 'dpc_sefaz_usuario_aba (antigo)', 2,
           (select count(*) from all_tables
             where owner = 'POSEIDON' and table_name = 'DPC_SEFAZ_USUARIO_ABA')
      from dual
    union all
    select 'dpc_sefaz_empresa_alerta (antigo)', 3,
           (select count(*) from all_tables
             where owner = 'POSEIDON' and table_name = 'DPC_SEFAZ_EMPRESA_ALERTA')
      from dual
    union all
    select 'dpc_dfe_usuario_empresa (novo)', 4,
           (select count(*) from all_tables
             where owner = 'POSEIDON' and table_name = 'DPC_DFE_USUARIO_EMPRESA')
      from dual
    union all
    select 'dpc_dfe_usuario_aba (novo)', 5,
           (select count(*) from all_tables
             where owner = 'POSEIDON' and table_name = 'DPC_DFE_USUARIO_ABA')
      from dual
    union all
    select 'dpc_dfe_painel_alerta (novo)', 6,
           (select count(*) from all_tables
             where owner = 'POSEIDON' and table_name = 'DPC_DFE_PAINEL_ALERTA')
      from dual
  ) order by ord;


-- ###########################################################################
--  1. RENAME  -  se a base tem os nomes antigos
-- ###########################################################################
--  Guardado nas DUAS pontas: renomeia so se o nome antigo existe E o novo
--  ainda nao. O dado, a PK, a unique, os indices e os grants vao junto - o
--  rename do Oracle nao copia nada, so troca a etiqueta.
--
--  ATENCAO OPERACIONAL: entre este rename e o deploy da ApiDPC que le o nome
--  novo, as tres telas devolvem ORA-00942. Rode com a janela combinada.

-- ---------- dpc_sefaz_usuario_empresa -> dpc_dfe_usuario_empresa ----------
declare
  qtd_antigo number;
  qtd_novo   number;
begin
  select count(*) into qtd_antigo from all_tables
   where owner = 'POSEIDON' and table_name = 'DPC_SEFAZ_USUARIO_EMPRESA';
  select count(*) into qtd_novo from all_tables
   where owner = 'POSEIDON' and table_name = 'DPC_DFE_USUARIO_EMPRESA';

  if qtd_antigo = 1 and qtd_novo = 0 then
    execute immediate 'alter table poseidon.dpc_sefaz_usuario_empresa rename to dpc_dfe_usuario_empresa';
    dbms_output.put_line('renomeada: dpc_sefaz_usuario_empresa -> dpc_dfe_usuario_empresa');
  elsif qtd_antigo = 1 and qtd_novo = 1 then
    dbms_output.put_line('ATENCAO: as DUAS existem. Nada foi feito - resolva a mao qual vale.');
  elsif qtd_novo = 1 then
    dbms_output.put_line('dpc_dfe_usuario_empresa ja esta com o nome novo.');
  else
    dbms_output.put_line('nenhuma das duas existe - a secao 2 vai criar.');
  end if;
end;

-- ---------- dpc_sefaz_usuario_aba -> dpc_dfe_usuario_aba ----------
declare
  qtd_antigo number;
  qtd_novo   number;
begin
  select count(*) into qtd_antigo from all_tables
   where owner = 'POSEIDON' and table_name = 'DPC_SEFAZ_USUARIO_ABA';
  select count(*) into qtd_novo from all_tables
   where owner = 'POSEIDON' and table_name = 'DPC_DFE_USUARIO_ABA';

  if qtd_antigo = 1 and qtd_novo = 0 then
    execute immediate 'alter table poseidon.dpc_sefaz_usuario_aba rename to dpc_dfe_usuario_aba';
    dbms_output.put_line('renomeada: dpc_sefaz_usuario_aba -> dpc_dfe_usuario_aba');
  elsif qtd_antigo = 1 and qtd_novo = 1 then
    dbms_output.put_line('ATENCAO: as DUAS existem. Nada foi feito - resolva a mao qual vale.');
  elsif qtd_novo = 1 then
    dbms_output.put_line('dpc_dfe_usuario_aba ja esta com o nome novo.');
  else
    dbms_output.put_line('nenhuma das duas existe - a secao 2 vai criar.');
  end if;
end;

-- ---------- dpc_sefaz_empresa_alerta -> dpc_dfe_painel_alerta ----------
--  Esta muda mais que o prefixo. "empresa_alerta" soa como atributo da filial,
--  quando o que a tabela guarda e o limiar que o PAINEL usa para pintar a
--  linha. Nao e permissao: e comportamento da tela.
declare
  qtd_antigo number;
  qtd_novo   number;
begin
  select count(*) into qtd_antigo from all_tables
   where owner = 'POSEIDON' and table_name = 'DPC_SEFAZ_EMPRESA_ALERTA';
  select count(*) into qtd_novo from all_tables
   where owner = 'POSEIDON' and table_name = 'DPC_DFE_PAINEL_ALERTA';

  if qtd_antigo = 1 and qtd_novo = 0 then
    execute immediate 'alter table poseidon.dpc_sefaz_empresa_alerta rename to dpc_dfe_painel_alerta';
    dbms_output.put_line('renomeada: dpc_sefaz_empresa_alerta -> dpc_dfe_painel_alerta');
  elsif qtd_antigo = 1 and qtd_novo = 1 then
    dbms_output.put_line('ATENCAO: as DUAS existem. Nada foi feito - resolva a mao qual vale.');
  elsif qtd_novo = 1 then
    dbms_output.put_line('dpc_dfe_painel_alerta ja esta com o nome novo.');
  else
    dbms_output.put_line('nenhuma das duas existe - a secao 2 vai criar.');
  end if;
end;


-- ###########################################################################
--  2. CREATE  -  se a base nao tem nenhuma das duas
-- ###########################################################################
--  Reproduz o que existe hoje em homologacao e em producao, com UMA diferenca
--  deliberada: aqui a PK e a UNIQUE nascem NOMEADAS. Nas tabelas criadas a mao
--  em 25/08/2026 elas ficaram com nome do sistema (SYS_C006353xx), e a secao 3
--  conserta isso. Instalacao nova ja nasce certa.

declare
  qtd number;
begin
  select count(*) into qtd from all_tables
   where owner = 'POSEIDON' and table_name = 'DPC_DFE_USUARIO_EMPRESA';

  if qtd = 0 then
    execute immediate q'[create table poseidon.dpc_dfe_usuario_empresa
    (
      id          NUMBER generated by default as identity not null,
      nroempresa  NUMBER(6) not null,
      usuario     VARCHAR2(100) not null,
      created_by  VARCHAR2(100) not null,
      created_at  DATE default sysdate not null,
      updated_by  VARCHAR2(100),
      updated_at  DATE,
      constraint DPC_DFE_USUARIO_EMPRESA_PK  primary key (id),
      constraint DPC_DFE_USUARIO_EMPRESA_UK1 unique (nroempresa, usuario)
    )
    tablespace TSD_POSEIDON]';
    dbms_output.put_line('criada: dpc_dfe_usuario_empresa');
  end if;
end;

declare
  qtd number;
begin
  select count(*) into qtd from all_tables
   where owner = 'POSEIDON' and table_name = 'DPC_DFE_USUARIO_ABA';

  if qtd = 0 then
    execute immediate q'[create table poseidon.dpc_dfe_usuario_aba
    (
      id          NUMBER generated by default as identity not null,
      usuario     VARCHAR2(100) not null,
      aba         VARCHAR2(20) not null,
      created_by  VARCHAR2(100) not null,
      created_at  DATE default sysdate not null,
      updated_by  VARCHAR2(100),
      updated_at  DATE,
      constraint DPC_DFE_USUARIO_ABA_PK  primary key (id),
      constraint DPC_DFE_USUARIO_ABA_UK1 unique (usuario, aba),
      constraint DPC_DFE_USUARIO_ABA_CK1 check (aba in ('DEVOLUCAO', 'COMPRAS', 'SUPRIMENTOS', 'SEM_CLASSIFICACAO'))
    )
    tablespace TSD_POSEIDON]';
    dbms_output.put_line('criada: dpc_dfe_usuario_aba');
  end if;
end;

declare
  qtd number;
begin
  select count(*) into qtd from all_tables
   where owner = 'POSEIDON' and table_name = 'DPC_DFE_PAINEL_ALERTA';

  if qtd = 0 then
    execute immediate q'[create table poseidon.dpc_dfe_painel_alerta
    (
      id                NUMBER generated by default as identity not null,
      nroempresa        NUMBER(6) not null,
      dias              NUMBER not null,
      cor_no_periodo    VARCHAR2(9),
      cor_fora_periodo  VARCHAR2(9),
      created_by        VARCHAR2(100) not null,
      created_at        DATE default sysdate not null,
      updated_by        VARCHAR2(100),
      updated_at        DATE,
      constraint DPC_DFE_PAINEL_ALERTA_PK  primary key (id),
      constraint DPC_DFE_PAINEL_ALERTA_UK1 unique (nroempresa)
    )
    tablespace TSD_POSEIDON]';
    dbms_output.put_line('criada: dpc_dfe_painel_alerta');
  end if;
end;


-- ###########################################################################
--  3. NOMES DE CONSTRAINT E DE INDICE
-- ###########################################################################
--  As tabelas criadas a mao deixaram a PK com nome do sistema
--  (SYS_C00635357) e a unique com um padrao proprio (uq_sefaz_usr_emp). O
--  rename da tabela NAO renomeia nada disso - ficaria uma
--  dpc_dfe_usuario_empresa cuja PK ainda se chama SYS_C00635357 e cuja unique
--  ainda diz "sefaz".
--
--  Os blocos abaixo procuram a constraint PELO TIPO, e nao pelo nome antigo:
--  o nome gerado pelo sistema e DIFERENTE em cada banco, entao um script que
--  citasse SYS_C00635357 funcionaria em homologacao e falharia em producao.
--
--  Renomear constraint e indice nao e visivel ao codigo: o PHP so cita nome de
--  tabela e de coluna.

-- ---------- PK das tres ----------
declare
  v_atual  varchar2(128);
  v_idx    varchar2(128);
begin
  for t in (select 'DPC_DFE_USUARIO_EMPRESA' as tab, 'DPC_DFE_USUARIO_EMPRESA_PK' as novo from dual union all
            select 'DPC_DFE_USUARIO_ABA',           'DPC_DFE_USUARIO_ABA_PK'           from dual union all
            select 'DPC_DFE_PAINEL_ALERTA',         'DPC_DFE_PAINEL_ALERTA_PK'         from dual) loop
    begin
      select constraint_name, index_name
        into v_atual, v_idx
        from all_constraints
       where owner = 'POSEIDON' and table_name = t.tab and constraint_type = 'P';

      if v_atual <> t.novo then
        execute immediate 'alter table poseidon.' || t.tab
                       || ' rename constraint "' || v_atual || '" to ' || t.novo;
        dbms_output.put_line(t.tab || ': PK ' || v_atual || ' -> ' || t.novo);
      end if;

      if v_idx is not null and v_idx <> t.novo then
        execute immediate 'alter index poseidon."' || v_idx || '" rename to ' || t.novo;
        dbms_output.put_line(t.tab || ': indice da PK ' || v_idx || ' -> ' || t.novo);
      end if;
    exception
      when no_data_found then
        dbms_output.put_line(t.tab || ': sem PK ou tabela ausente - nada a fazer.');
      when others then
        dbms_output.put_line(t.tab || ': FALHOU no ajuste da PK -> ' || sqlerrm);
    end;
  end loop;
end;

-- ---------- UNIQUE das tres ----------
declare
  v_atual  varchar2(128);
  v_idx    varchar2(128);
begin
  for t in (select 'DPC_DFE_USUARIO_EMPRESA' as tab, 'DPC_DFE_USUARIO_EMPRESA_UK1' as novo from dual union all
            select 'DPC_DFE_USUARIO_ABA',           'DPC_DFE_USUARIO_ABA_UK1'           from dual union all
            select 'DPC_DFE_PAINEL_ALERTA',         'DPC_DFE_PAINEL_ALERTA_UK1'         from dual) loop
    begin
      select constraint_name, index_name
        into v_atual, v_idx
        from all_constraints
       where owner = 'POSEIDON' and table_name = t.tab and constraint_type = 'U';

      if v_atual <> t.novo then
        execute immediate 'alter table poseidon.' || t.tab
                       || ' rename constraint "' || v_atual || '" to ' || t.novo;
        dbms_output.put_line(t.tab || ': UK ' || v_atual || ' -> ' || t.novo);
      end if;

      if v_idx is not null and v_idx <> t.novo then
        execute immediate 'alter index poseidon."' || v_idx || '" rename to ' || t.novo;
        dbms_output.put_line(t.tab || ': indice da UK ' || v_idx || ' -> ' || t.novo);
      end if;
    exception
      when no_data_found then
        dbms_output.put_line(t.tab || ': sem UNIQUE ou tabela ausente - nada a fazer.');
      when others then
        dbms_output.put_line(t.tab || ': FALHOU no ajuste da UK -> ' || sqlerrm);
    end;
  end loop;
end;

-- ---------- o CHECK do aba ----------
--  So o de dpc_dfe_usuario_aba tem check nomeado (ck_sefaz_aba). Os demais
--  CHECK das tres tabelas sao os NOT NULL implicitos, gerados pelo Oracle -
--  esses ficam como estao, e o modulo tambem nao nomeia NOT NULL.
declare
  v_atual varchar2(128);
begin
  begin
    select constraint_name into v_atual
      from all_constraints
     where owner = 'POSEIDON' and table_name = 'DPC_DFE_USUARIO_ABA'
       and constraint_type = 'C' and constraint_name not like 'SYS%';

    if v_atual <> 'DPC_DFE_USUARIO_ABA_CK1' then
      execute immediate 'alter table poseidon.dpc_dfe_usuario_aba rename constraint "'
                     || v_atual || '" to DPC_DFE_USUARIO_ABA_CK1';
      dbms_output.put_line('DPC_DFE_USUARIO_ABA: CK ' || v_atual || ' -> DPC_DFE_USUARIO_ABA_CK1');
    end if;
  exception
    when no_data_found then
      dbms_output.put_line('DPC_DFE_USUARIO_ABA: sem check nomeado - nada a fazer.');
    when too_many_rows then
      dbms_output.put_line('DPC_DFE_USUARIO_ABA: MAIS DE UM check nomeado - resolva a mao.');
    when others then
      dbms_output.put_line('DPC_DFE_USUARIO_ABA: FALHOU no ajuste do CK -> ' || sqlerrm);
  end;
end;


-- ###########################################################################
--  4. COMENTARIOS
-- ###########################################################################
--  As 23 colunas, e nao apenas as 7 que tinham comentario. Sem isto o
--  invariante "coluna sem comentario = 0" do 01_04_validacao_dbeaver.sql passa a
--  acusar 16, porque estas tres entram no padrao DPC_DFE% depois do rename.
--
--  comment on e idempotente por natureza: reexecutar reescreve igual.

comment on table poseidon.dpc_dfe_usuario_empresa is
  'Modulo DFe, bloco de TELAS: quais filiais cada usuario ve. Renomeada de DPC_SEFAZ_USUARIO_EMPRESA em 09/09/2026, quando o modulo passou a ter um prefixo unico. Lida por DUAS telas - o dashboard Documentos Fiscais e a listagem de NF-e capturadas. SEM LINHA AQUI O USUARIO NAO VE NADA, e sem erro: o repositorio curto-circuita e devolve HTTP 200 com lista vazia, indistinguivel de "nao ha nota no periodo". Escrita pela tela Sefaz > Parametros.';

comment on column poseidon.dpc_dfe_usuario_empresa.id is
  'PK. IDENTITY COLUMN (generated by default as identity), e nao trigger + sequence como o resto do modulo - esta tabela nasceu pelo lado do front, no card #3235. Identity nao e exotico no schema: 43 das 1.098 tabelas usam. Mantida assim porque trocar mudaria o contrato dos tres repositorios que fazem insert.';
comment on column poseidon.dpc_dfe_usuario_empresa.nroempresa is
  'FK logica: consinco.ge_empresa.nroempresa. Casa tambem com dpc_dfe_empresa.nro_empresa, a identidade fiscal do motor. Nome sem prefixo nro_ e convencao do banco legado - aparece em 237 arquivos do DPC - e por isso NAO foi renomeada.';
comment on column poseidon.dpc_dfe_usuario_empresa.usuario is
  'Login: consinco.dpc_usuario.usuario.';
comment on column poseidon.dpc_dfe_usuario_empresa.created_by is
  'Usuario que criou a permissao, gravado pela tela Sefaz > Parametros.';
comment on column poseidon.dpc_dfe_usuario_empresa.created_at is
  'Quando a permissao foi criada. Default sysdate.';
comment on column poseidon.dpc_dfe_usuario_empresa.updated_by is
  'Usuario da ultima alteracao. Nulo enquanto nunca foi alterada.';
comment on column poseidon.dpc_dfe_usuario_empresa.updated_at is
  'Quando foi alterada pela ultima vez. Nulo enquanto nunca foi alterada.';

comment on table poseidon.dpc_dfe_usuario_aba is
  'Modulo DFe, bloco de TELAS: quais categorias cada usuario ve no dashboard Documentos Fiscais. Renomeada de DPC_SEFAZ_USUARIO_ABA em 09/09/2026. Lida SO pelo dashboard: a listagem de NF-e capturadas nao usa, por decisao registrada no docblock do SefazNfeRepository - categoria e conceito do dashboard, nao daquela listagem. Escrita pela tela Sefaz > Parametros.';

comment on column poseidon.dpc_dfe_usuario_aba.id is
  'PK. IDENTITY COLUMN, pelo mesmo motivo de dpc_dfe_usuario_empresa.id.';
comment on column poseidon.dpc_dfe_usuario_aba.usuario is
  'Login: consinco.dpc_usuario.usuario.';
comment on column poseidon.dpc_dfe_usuario_aba.aba is
  'Categoria: DEVOLUCAO | COMPRAS | SUPRIMENTOS | SEM_CLASSIFICACAO. Espelha SefazParamUsuarioAbaRepository::ABAS_VALIDAS e a constante ABAS_DASHBOARD do SefazDocumentosFiscaisRepository - os tres tem de andar juntos. Garantido pelo DPC_DFE_USUARIO_ABA_CK1.';
comment on column poseidon.dpc_dfe_usuario_aba.created_by is
  'Usuario que criou a permissao, gravado pela tela Sefaz > Parametros.';
comment on column poseidon.dpc_dfe_usuario_aba.created_at is
  'Quando a permissao foi criada. Default sysdate.';
comment on column poseidon.dpc_dfe_usuario_aba.updated_by is
  'Usuario da ultima alteracao. Nulo enquanto nunca foi alterada.';
comment on column poseidon.dpc_dfe_usuario_aba.updated_at is
  'Quando foi alterada pela ultima vez. Nulo enquanto nunca foi alterada.';

comment on table poseidon.dpc_dfe_painel_alerta is
  'Modulo DFe, bloco de TELAS: a partir de quantos dias a nota pendente aparece como atrasada, por filial, e com que cor. Renomeada de DPC_SEFAZ_EMPRESA_ALERTA em 09/09/2026, e o nome mudou mais que o prefixo de proposito: "empresa_alerta" soa como atributo da filial, quando o que a tabela guarda e comportamento do PAINEL. NAO e permissao. ATENCAO: o painel "atraso maior que N dias" usa JOIN com esta tabela - filial sem linha aqui NAO APARECE naquele painel, e em 09/09/2026 a tabela estava vazia.';

comment on column poseidon.dpc_dfe_painel_alerta.id is
  'PK. IDENTITY COLUMN, pelo mesmo motivo de dpc_dfe_usuario_empresa.id.';
comment on column poseidon.dpc_dfe_painel_alerta.nroempresa is
  'FK logica: consinco.ge_empresa.nroempresa. Uma linha por filial, garantido pela DPC_DFE_PAINEL_ALERTA_UK1.';
comment on column poseidon.dpc_dfe_painel_alerta.dias is
  'Limiar de aging: ate este numero de dias a nota pendente esta dentro do prazo. Acima dele entra no painel de atraso e muda de cor.';
comment on column poseidon.dpc_dfe_painel_alerta.cor_no_periodo is
  'Hex #RRGGBB para aging menor ou igual a dias. Lida PELO NOME no front, em documentos-fiscais/components/Main.vue - por isso a coluna nao foi renomeada na padronizacao de 09/09/2026.';
comment on column poseidon.dpc_dfe_painel_alerta.cor_fora_periodo is
  'Hex #RRGGBB para aging maior que dias. Mesma observacao de cor_no_periodo: lida pelo nome no front.';
comment on column poseidon.dpc_dfe_painel_alerta.created_by is
  'Usuario que criou o limiar, gravado pela tela Sefaz > Parametros.';
comment on column poseidon.dpc_dfe_painel_alerta.created_at is
  'Quando o limiar foi criado. Default sysdate.';
comment on column poseidon.dpc_dfe_painel_alerta.updated_by is
  'Usuario da ultima alteracao. Nulo enquanto nunca foi alterado.';
comment on column poseidon.dpc_dfe_painel_alerta.updated_at is
  'Quando foi alterado pela ultima vez. Nulo enquanto nunca foi alterado.';


-- ###########################################################################
--  5. CONFERENCIA
-- ###########################################################################

--  5a. As tres com o nome novo, e nenhuma com o antigo.
--      ESPERADO: 3 linhas "novo / existe" e nenhuma linha de antigo.
select table_name, 'existe' as situacao
  from all_tables
 where owner = 'POSEIDON'
   and table_name in ('DPC_DFE_USUARIO_EMPRESA', 'DPC_DFE_USUARIO_ABA', 'DPC_DFE_PAINEL_ALERTA',
                      'DPC_SEFAZ_USUARIO_EMPRESA', 'DPC_SEFAZ_USUARIO_ABA', 'DPC_SEFAZ_EMPRESA_ALERTA')
 order by table_name;

--  5b. Nome de constraint e de indice. ESPERADO: nenhum SYS_ e nenhum uq_/ck_.
select c.table_name, c.constraint_type, c.constraint_name, c.index_name
  from all_constraints c
 where c.owner = 'POSEIDON'
   and c.table_name in ('DPC_DFE_USUARIO_EMPRESA', 'DPC_DFE_USUARIO_ABA', 'DPC_DFE_PAINEL_ALERTA')
   and c.constraint_type in ('P', 'U')
 order by c.table_name, c.constraint_type;

select table_name, index_name, uniqueness
  from all_indexes
 where owner = 'POSEIDON'
   and table_name in ('DPC_DFE_USUARIO_EMPRESA', 'DPC_DFE_USUARIO_ABA', 'DPC_DFE_PAINEL_ALERTA')
 order by table_name, index_name;

--  5c. Comentarios. ESPERADO: 3 tabelas comentadas e 23 colunas, 0 sem.
select count(distinct t.table_name)                                      as tabelas,
       count(*)                                                          as colunas,
       sum(case when m.comments is null then 1 else 0 end)                as sem_comentario
  from all_tab_columns t
  left join all_col_comments m
         on m.owner = t.owner and m.table_name = t.table_name and m.column_name = t.column_name
 where t.owner = 'POSEIDON'
   and t.table_name in ('DPC_DFE_USUARIO_EMPRESA', 'DPC_DFE_USUARIO_ABA', 'DPC_DFE_PAINEL_ALERTA');

--  5d. O dado sobreviveu ao rename. ESPERADO: as contagens de antes.
select 'dpc_dfe_usuario_empresa' as tabela, count(*) as linhas,
       count(distinct usuario) as usuarios from poseidon.dpc_dfe_usuario_empresa
union all
select 'dpc_dfe_usuario_aba', count(*), count(distinct usuario) from poseidon.dpc_dfe_usuario_aba
union all
select 'dpc_dfe_painel_alerta', count(*), null from poseidon.dpc_dfe_painel_alerta;

--  5e. Filial com permissao que o motor nao conhece. E INFORMACAO, nao erro:
--      a permissao e por nroempresa do ERP e pode citar filial que ainda nao
--      entrou no modulo. ESPERADO em base consistente: nenhuma linha.
select distinct p.nroempresa
  from poseidon.dpc_dfe_usuario_empresa p
 where not exists (select 1 from poseidon.dpc_dfe_empresa e
                    where e.nro_empresa = p.nroempresa)
 order by 1;
-- ============================================================================
