-- ============================================================================
--  MODULO DFe - MANIFESTACAO DO DESTINATARIO (ARQUIVO 04_02)
-- ============================================================================
--  Fases 2 a 4: Ciencia automatica, Confirmacao automatica e acao manual na
--  tela do Monitor NF-e. Este arquivo acrescenta o que falta no banco para as
--  tres - a fundacao (fila por evento, prazos, UK, trancas) ja veio no 04_01.
--
--  ==========================================================================
--   POR QUE ESTAS DUAS MUDANCAS
--  ==========================================================================
--  1) DTA_INICIO_MANIF_AUTO_CONF em dpc_dfe_empresa
--     A Confirmacao automatica (Fase 3) so vale DAQUI PRA FRENTE: decisao do
--     usuario em 24/09/2026. A empresa 29 sozinha tem 707 notas ja
--     escrituradas dentro do prazo de 90 dias (6.562 somando as 15) - ligar a
--     automacao sem corte de data despejaria esse backlog inteiro como atos
--     fiscais reais e irreversiveis nos primeiros ciclos. A coluna funciona
--     como uma SEGUNDA trava, alem de status_manif_auto_confirmacao: mesmo
--     com a flag em 'S', sem data preenchida a Confirmacao automatica nao
--     roda (NULL = automacao nunca comecou a contar). Notas mais antigas que
--     a data continuam alcancaveis so pela tela manual (Fase 4), que nao usa
--     este corte.
--
--  2) DPC_DFE_USUARIO_PERMISSAO (tabela nova)
--     A Fase 4 poe um botao real de manifestar na tela - acao fiscal
--     irreversivel, entao precisa de uma permissao propria, nao basta ver a
--     empresa. O modulo ja resolve "o usuario pode X" com uma tabela onde a
--     LINHA EXISTIR e a permissao (dpc_dfe_usuario_aba faz o mesmo para
--     categoria). Repete o padrao em vez de reaproveitar dpc_dfe_usuario_aba,
--     porque aba e um dominio fechado por natureza (as 4 categorias do
--     dashboard) e permissao e um dominio que cresce - hoje so MANIFESTAR,
--     amanha pode ter outras acoes da tela sem precisar de tabela nova.
--
--  ==========================================================================
--   UM CAMINHO SO
--  ==========================================================================
--  Idempotente: rodar duas vezes produz o mesmo resultado da primeira.
--
--  A coluna nova foi acrescentada tambem ao 01_01_estrutura_dbeaver.sql e a
--  tabela nova ao 03_01_parametrizacao_telas_dbeaver.sql, pelo mesmo motivo
--  do 04_01: um rebuild de homolog nao pode recriar a base sem elas.
--
--  ==========================================================================
--   COMO RODAR (DBeaver)
--  ==========================================================================
--  Conectado como POSEIDON, arquivo INTEIRO com Alt+X. Sem "/" para terminar
--  bloco. E CRLF de proposito: em LF o divisor de statements do DBeaver corta
--  o bloco PL/SQL no fim do IF e devolve PLS-00103.
--
--  LIGUE O DBMS_OUTPUT (aba Output do editor de SQL).
--
--  O COMMIT e explicito, no fim. Ao final ha um SELECT de conferencia.
-- ============================================================================


-- ============================================================================
--  SECAO 1 - CORTE DE DATA PARA A CONFIRMACAO AUTOMATICA
-- ============================================================================
declare
  qtd number;
begin
  select count(*) into qtd from all_tab_columns
   where owner = 'POSEIDON' and table_name = 'DPC_DFE_EMPRESA'
     and column_name = 'DTA_INICIO_MANIF_AUTO_CONF';

  if qtd = 0 then
    execute immediate 'alter table poseidon.dpc_dfe_empresa add (dta_inicio_manif_auto_conf DATE)';
    dbms_output.put_line('DPC_DFE_EMPRESA: acrescentada -> dta_inicio_manif_auto_conf');
  else
    dbms_output.put_line('DPC_DFE_EMPRESA: ja existia   -> dta_inicio_manif_auto_conf');
  end if;
exception
  when others then
    dbms_output.put_line('DPC_DFE_EMPRESA: FALHOU em dta_inicio_manif_auto_conf -> ' || sqlerrm);
end;

-- ============================================================================
--  SECAO 2 - TABELA DPC_DFE_USUARIO_PERMISSAO
-- ============================================================================
declare
  qtd number;
begin
  select count(*) into qtd from all_tables
   where owner = 'POSEIDON' and table_name = 'DPC_DFE_USUARIO_PERMISSAO';

  if qtd = 0 then
    execute immediate q'[create table poseidon.dpc_dfe_usuario_permissao
    (
      id          NUMBER generated by default as identity not null,
      usuario     VARCHAR2(100) not null,
      permissao   VARCHAR2(20) not null,
      created_by  VARCHAR2(100) not null,
      created_at  DATE default sysdate not null,
      updated_by  VARCHAR2(100),
      updated_at  DATE,
      constraint DPC_DFE_USUARIO_PERMISSAO_PK  primary key (id),
      constraint DPC_DFE_USUARIO_PERMISSAO_UK1 unique (usuario, permissao),
      constraint DPC_DFE_USUARIO_PERMISSAO_CK1 check (permissao in ('MANIFESTAR'))
    )
    tablespace TSD_POSEIDON]';
    dbms_output.put_line('criada: dpc_dfe_usuario_permissao');
  else
    dbms_output.put_line('dpc_dfe_usuario_permissao ja existe.');
  end if;
exception
  when others then
    dbms_output.put_line('DPC_DFE_USUARIO_PERMISSAO: FALHOU -> ' || sqlerrm);
end;

-- ============================================================================
--  SECAO 3 - COMENTARIOS
-- ============================================================================
comment on column poseidon.dpc_dfe_empresa.dta_inicio_manif_auto_conf is
  'Data a partir da qual a Confirmacao automatica (210200) passa a considerar as notas desta empresa. NULL = a automacao nao roda, mesmo com status_manif_auto_confirmacao=S (segunda trava). Decisao de 24/09/2026: nao drenar o backlog anterior (707 notas so na empresa 29 dentro do prazo de 90 dias) por automacao, so por acao manual na tela.';

comment on table poseidon.dpc_dfe_usuario_permissao is
  'Permissoes de acao do usuario nas telas do modulo DFe. LINHA EXISTIR e a permissao, mesmo padrao de dpc_dfe_usuario_aba. Hoje so a permissao MANIFESTAR (botao de manifestacao manual no Monitor NF-e), pensada para crescer sem precisar de tabela nova.';

comment on column poseidon.dpc_dfe_usuario_permissao.id is
  'Identity, nao trigger + sequence.';

comment on column poseidon.dpc_dfe_usuario_permissao.usuario is
  'Login: consinco.dpc_usuario.usuario.';

comment on column poseidon.dpc_dfe_usuario_permissao.permissao is
  'Hoje so MANIFESTAR. Garantido por DPC_DFE_USUARIO_PERMISSAO_CK1; espelha SefazParamUsuarioPermissaoRepository::PERMISSOES_VALIDAS.';

comment on column poseidon.dpc_dfe_usuario_permissao.created_by is
  'Login de quem concedeu a permissao.';

comment on column poseidon.dpc_dfe_usuario_permissao.created_at is
  'Quando a permissao foi concedida.';

comment on column poseidon.dpc_dfe_usuario_permissao.updated_by is
  'Reservado para uso futuro; hoje a remocao e DELETE fisico, sem update.';

comment on column poseidon.dpc_dfe_usuario_permissao.updated_at is
  'Reservado para uso futuro; hoje a remocao e DELETE fisico, sem update.';

commit;

-- ============================================================================
--  SECAO 4 - CONFERENCIA
-- ============================================================================
select 'coluna' as tipo, column_name as objeto,
       data_type || '(' || data_length || ')' as detalhe,
       nullable as obs
  from all_tab_columns
 where owner = 'POSEIDON' and table_name = 'DPC_DFE_EMPRESA'
   and column_name = 'DTA_INICIO_MANIF_AUTO_CONF'
union all
select 'tabela', table_name, 'existe', null
  from all_tables
 where owner = 'POSEIDON' and table_name = 'DPC_DFE_USUARIO_PERMISSAO'
union all
select 'constraint', c.constraint_name,
       listagg(cc.column_name, ',') within group (order by cc.position), c.constraint_type
  from all_constraints c
  join all_cons_columns cc on cc.owner = c.owner and cc.constraint_name = c.constraint_name
 where c.owner = 'POSEIDON'
   and c.constraint_name in ('DPC_DFE_USUARIO_PERMISSAO_PK','DPC_DFE_USUARIO_PERMISSAO_UK1','DPC_DFE_USUARIO_PERMISSAO_CK1')
 group by c.constraint_name, c.constraint_type
 order by 1, 2;
