-- ============================================================================
--  MODULO DFe - PREFERENCIA DE COLUNAS POR USUARIO (ARQUIVO 06_01)
-- ============================================================================
--  Tabela nova: poseidon.dpc_dfe_usuario_coluna
--
--  ==========================================================================
--   POR QUE SAIR DO LOCALSTORAGE
--  ==========================================================================
--  A escolha de colunas do Monitor NF-e vivia so no localStorage do
--  navegador (chave 'sefaz-nfe-colunas'). Isso resolve "por maquina", nao
--  "por usuario": quem troca de computador, usa aba anonima ou tem o cache
--  limpo perde a configuracao e volta ao padrao.
--
--  Pedido da equipe fiscal em 01/10/2026: colunas padrao personalizaveis POR
--  USUARIO. Para a preferencia seguir a pessoa e preciso guardar no servidor.
--
--  ==========================================================================
--   POR QUE UMA TABELA, E NAO UMA COLUNA EM ALGUM CADASTRO
--  ==========================================================================
--  O modulo ja resolve "preferencia do usuario" com tabela propria -
--  dpc_dfe_usuario_empresa, dpc_dfe_usuario_aba, dpc_dfe_usuario_permissao.
--  Esta repete o padrao, com duas diferencas que importam:
--
--  1) Nas outras, a LINHA EXISTIR e a informacao (tem permissao / ve a aba).
--     Aqui a linha carrega CONTEUDO: a lista de colunas escolhidas.
--
--  2) Tem DSC_TELA na chave. A mesma tabela serve o Monitor de CT-e e o de
--     NFS-e quando eles ganharem catalogo de colunas, sem DDL nova. Custa uma
--     coluna agora e evita duas tabelas depois.
--
--  ==========================================================================
--   POR QUE A LISTA E TEXTO, E NAO UMA LINHA POR COLUNA
--  ==========================================================================
--  A escolha e lida e gravada SEMPRE INTEIRA - a tela manda o conjunto todo
--  ao confirmar o modal, nunca uma coluna isolada. Normalizar em uma linha
--  por coluna daria 30+ linhas por usuario, um DELETE+INSERT em bloco a cada
--  salvamento, e nenhuma consulta que se beneficie disso: ninguem vai
--  perguntar "quais usuarios ligaram a coluna X".
--
--  A ORDEM das colunas tambem e informacao (o usuario reordena na tela), e
--  ordem em linhas separadas exigiria mais uma coluna de sequencia.
--
--  VARCHAR2(4000) comporta com folga: hoje sao 42 colunas, e a soma dos
--  nomes de campo nao passa de ~900 caracteres. O repositorio recusa acima
--  disso em vez de deixar o Oracle truncar.
--
--  ==========================================================================
--   UM CAMINHO SO
--  ==========================================================================
--  Idempotente: rodar duas vezes produz o mesmo resultado da primeira.
--
--  O bloco PL/SQL segue o molde do 04_02, e nao por gosto: com aspas simples
--  na DDL multilinha e um terminador / no fim, o DBeaver corta o bloco e
--  devolve PLS-00103 (end-of-file) seguido de ORA-00900. Com q'[...]' e sem
--  a barra, ele envia o bloco inteiro. Nao trocar de volta.
--
--  NAO esta espelhada no 03_01_parametrizacao_telas, pela mesma razao do
--  04_02: aquele arquivo narra a migracao historica de tres tabelas
--  dpc_sefaz_* -> dpc_dfe_*, e esta nunca teve nome antigo. Consequencia:
--  pular este bloco numa instalacao nova deixa a tela sem preferencia de
--  coluna por usuario - o front cai no localStorage e segue funcionando,
--  entao nao quebra, so perde a funcionalidade.
--
--  ==========================================================================
--   COMO RODAR (DBeaver)
--  ==========================================================================
--  Conectado como POSEIDON, arquivo INTEIRO com Alt+X.
-- ============================================================================


-- ============================================================================
--  SECAO 1 - TABELA
-- ============================================================================

declare
  qtd number;
begin
  select count(*) into qtd from all_tables
   where owner = 'POSEIDON' and table_name = 'DPC_DFE_USUARIO_COLUNA';

  if qtd = 0 then
    execute immediate q'[create table poseidon.dpc_dfe_usuario_coluna
    (
      id          NUMBER generated by default as identity not null,
      usuario     VARCHAR2(100) not null,
      dsc_tela    VARCHAR2(30) not null,
      dsc_colunas VARCHAR2(4000) not null,
      created_by  VARCHAR2(100) not null,
      created_at  DATE default sysdate not null,
      updated_by  VARCHAR2(100),
      updated_at  DATE,
      constraint DPC_DFE_USUARIO_COLUNA_PK  primary key (id),
      constraint DPC_DFE_USUARIO_COLUNA_UK1 unique (usuario, dsc_tela),
      constraint DPC_DFE_USUARIO_COLUNA_CK1 check (dsc_tela in ('NFE','CTE','NFSE'))
    )
    tablespace TSD_POSEIDON]';
    dbms_output.put_line('criada: dpc_dfe_usuario_coluna');
  else
    dbms_output.put_line('dpc_dfe_usuario_coluna ja existe.');
  end if;
exception
  when others then
    dbms_output.put_line('DPC_DFE_USUARIO_COLUNA: FALHOU -> ' || sqlerrm);
end;


-- ============================================================================
--  SECAO 2 - COMENTARIOS
-- ============================================================================

comment on table poseidon.dpc_dfe_usuario_coluna is
    'Colunas escolhidas por usuario em cada tela do modulo DFe. Substitui o localStorage, que era por navegador e nao acompanhava a pessoa.';

comment on column poseidon.dpc_dfe_usuario_coluna.usuario is
    'Login do usuario, mesmo dominio de dpc_dfe_usuario_aba.usuario.';

comment on column poseidon.dpc_dfe_usuario_coluna.dsc_tela is
    'Qual tela. Hoje so NFE; existe para CT-e e NFS-e usarem a mesma tabela sem DDL nova.';

comment on column poseidon.dpc_dfe_usuario_coluna.dsc_colunas is
    'Campos escolhidos, separados por virgula e NA ORDEM em que a tela os exibe. Gravado inteiro a cada salvamento.';


-- ============================================================================
--  SECAO 3 - CONFERENCIA
-- ============================================================================

select 'tabela' as tipo, table_name as objeto, null as detalhe
  from all_tables
 where owner = 'POSEIDON' and table_name = 'DPC_DFE_USUARIO_COLUNA'
union all
select 'constraint', c.constraint_name,
       listagg(cc.column_name, ',') within group (order by cc.position)
  from all_constraints c
  join all_cons_columns cc on cc.owner = c.owner and cc.constraint_name = c.constraint_name
 where c.owner = 'POSEIDON'
   and c.constraint_name in ('DPC_DFE_USUARIO_COLUNA_PK','DPC_DFE_USUARIO_COLUNA_UK1','DPC_DFE_USUARIO_COLUNA_CK1')
 group by c.constraint_name
 order by 1, 2;
