-- ===========================================================================
--  BLOCO 11_01 - MODELOS salvos do Relatorio Avancado
-- ===========================================================================
--
--  Banco: Oracle (homolog)        Schema: poseidon
--  Tabela nova: poseidon.dpc_dfe_usuario_modelo
--  Rollback: 11_99_rollback_modelos_usuario_dbeaver.sql
--
--  ==========================================================================
--   POR QUE
--  ==========================================================================
--  Sefaz > Relatorios Avancados vira uma BUSCA AVANCADA, no desenho da Qive
--  (pedido do usuario em 05/10/2026: "os relatorios avancados estao identicos
--  aos relatorios e bem diferentes dos relatorios avancados da Qive").
--
--  O que falta para merecer o nome e o MODELO SALVO: a equipe fiscal fecha o
--  mes na Qive com o "Modelo Conferencia Mensal CTE", escolhe o modelo, troca
--  o periodo e exporta. Esta tabela guarda esses modelos.
--
--  Dois tipos, independentes entre si (tip_modelo):
--    F = filtro  - empresas, periodo, papel, busca, chaves, filtros da familia
--    C = colunas - a lista de colunas, na ordem escolhida
--
--  NAO substitui dpc_dfe_usuario_coluna (bloco 06_01), que guarda UMA escolha
--  corrente por tela. Esta aqui guarda N escolhas COM NOME, para reusar.
--
--  ==========================================================================
--   DESENHO
--  ==========================================================================
--  dsc_conteudo e CLOB com JSON. Nao e tabela normalizada de proposito: o
--  conteudo e um retrato da TELA (cada familia tem filtros proprios, e eles
--  mudam quando a tela muda). Normalizar exigiria uma tabela por familia e
--  migracao a cada coluna nova. O servidor so valida que e JSON e cabe no
--  teto; quem interpreta e a tela que salvou.
--
--  A UK (usuario, dsc_tela, tip_modelo, nom_modelo) e o que impede dois
--  modelos com o mesmo nome para a mesma pessoa na mesma tela - o erro vira
--  mensagem na tela, nao linha duplicada.
--
--  O modelo e PESSOAL: usuario vem sempre do token, nunca de parametro.
--  Modelo compartilhado com a equipe ficou de fora por decisao do usuario.
--
--  ==========================================================================
--   ANTES DE RODAR: CONFIRA SE JA RODOU
--  ==========================================================================
--  Rode o SELECT do fim do arquivo. Se a tabela ja aparecer, nao rode de novo
--  (o create repetido da ORA-00955, inofensivo mas desnecessario).
--
--  Sem bloco PL/SQL, pela regra do modulo: o divisor do DBeaver corta bloco e
--  o Oracle devolve PLS-00103.
--
--  Rodar no DBeaver com Execute script (Alt+X).
-- ===========================================================================


create table poseidon.dpc_dfe_usuario_modelo
(
  id           NUMBER generated by default as identity not null,
  usuario      VARCHAR2(100) not null,
  dsc_tela     VARCHAR2(10)  not null,
  tip_modelo   CHAR(1)       not null,
  nom_modelo   VARCHAR2(60)  not null,
  dsc_conteudo CLOB          not null,
  created_by   VARCHAR2(100) not null,
  created_at   DATE default sysdate not null,
  updated_by   VARCHAR2(100),
  updated_at   DATE,
  constraint DPC_DFE_USUARIO_MODELO_PK  primary key (id),
  constraint DPC_DFE_USUARIO_MODELO_UK1 unique (usuario, dsc_tela, tip_modelo, nom_modelo),
  constraint DPC_DFE_USUARIO_MODELO_CK1 check (dsc_tela in ('NFE', 'CTE', 'NFSE')),
  constraint DPC_DFE_USUARIO_MODELO_CK2 check (tip_modelo in ('F', 'C'))
)
tablespace TSD_POSEIDON;

comment on table poseidon.dpc_dfe_usuario_modelo is
  'Modelos nomeados de filtro (F) e de colunas (C) do Relatorio Avancado. Pessoais: o usuario vem do token.';

comment on column poseidon.dpc_dfe_usuario_modelo.usuario is
  'Login dono do modelo. Vem do token - nunca de parametro, senao um usuario sobrescreveria o modelo do outro.';

comment on column poseidon.dpc_dfe_usuario_modelo.dsc_tela is
  'Familia: NFE, CTE ou NFSE. Vem da ROTA, nao do cliente.';

comment on column poseidon.dpc_dfe_usuario_modelo.tip_modelo is
  'F = filtro (empresas, periodo, papel, busca, chaves, filtros da familia); C = colunas, na ordem.';

comment on column poseidon.dpc_dfe_usuario_modelo.nom_modelo is
  'Nome que a pessoa deu. Unico por usuario+tela+tipo (UK1).';

comment on column poseidon.dpc_dfe_usuario_modelo.dsc_conteudo is
  'JSON com o retrato da tela. Nao normalizado de proposito: cada familia tem filtros proprios e eles mudam com a tela.';


-- ===========================================================================
--  CONFERENCIA - esperado: 1 tabela, 10 colunas, 4 constraints
-- ===========================================================================

select 'tabela' tipo, table_name nome, to_char(null) detalhe
  from all_tables
 where owner = 'POSEIDON' and table_name = 'DPC_DFE_USUARIO_MODELO'
union all
select 'coluna', column_name,
       data_type || case when data_length is not null and data_type like 'VARCHAR2%'
                         then '(' || data_length || ')' else '' end
  from all_tab_columns
 where owner = 'POSEIDON' and table_name = 'DPC_DFE_USUARIO_MODELO'
union all
select 'constraint', constraint_name, constraint_type
  from all_constraints
 where owner = 'POSEIDON' and table_name = 'DPC_DFE_USUARIO_MODELO'
   and constraint_name like 'DPC_DFE_USUARIO_MODELO%'
 order by 1, 2;